# Site settings
title: Audible Electricity
email: hi@audibleelectricity.com
description: > 
  Audible Electricity is a concert series for 
  improvised, experimental and other music. Presented  
  by LuvSound in Milwaukee Wisconsin.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://audibleelectricity.com" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
future: true
